[package]
name = "devos"
version = "0.1.0"
authors = ["Pepijn de Vos <pepijndevos@gmail.com>"]

[dependencies]
rlibc = "1.0.0"
compiler_builtins = { git = "https://github.com/rust-lang-nursery/compiler-builtins" }

[lib]
crate-type = ["staticlib"]
